### PR TITLE
New Essentia Window

### PR DESCRIPTION
**Pull request by 1vasari**
Does everything the old UI does + buying boosts that last multiple weeks.

Boosts

If you hover each icon you'll see a tooltip describing what each boost is.

Get More E

### CODE REVIEW

**Comment by dmcbride** [comment]
Issues here:

On the "Get More Essentia" tab:
* Invite a friend puts the new window behind the essentia window.
* The redeem input field's font is too big, and putting in a code there will actually not be able to display the whole thing (I'm missing about a character and a quarter).
* Really, all the buttons and fonts just seem huge to me.

On the "Boosts" tab:
* Again, everything just seems huge.
* The scroll bar on the right - it'd probably be much better if it didn't also scroll the tabs.
* Can we make it so the max number of weeks you can enter here is int(empire.essentia / 5) ?  As in, you can't put in more than the amount of essentia you have?
* Can we get rid of the number fields (and its extra help) when essentia < 50? Otherwise we'll end up with newbies spending all their tutorial essentia on a single boost and be unable to continue.

Overall:
* The inactive tab doesn't look like a tab.  Can it still show up, even if it's not as bright as the active tab?
* Escape key doesn't close the window.

Thanks, Vas!

**Comment by xHusky** [comment]
The Essentia window's layout should be reworked to make its use easier for players. Parallel layouts like this have proven to be more appealing: mockup

**Comment by 1vasari** [comment]
As requested I've reduced the sizing of the elements in the Essentia window down. Furthermore, I've implemented the limiting regarding purchasing of boosts as specified and made the windows disappear when escape is hit.

However, I've not been able to do anything with the tabs. At the moment we're using `react-tabs` to do the tabs. They're pretty good, except they won't do what you want without hacking them. I'm considering either forking that repo and making a custom version for our use or just starting from scratch and making a tabbing component which fits our needs exactly. Either way, keeping the tabs at the top and changing their styles isn't really doable at the moment.

**Comment by dmcbride** [comment]
Every time I get a new commit from you, vas, I forget to run npm install before gulp. :)

**Comment by 1vasari** [comment]
@dmcbride I believe I have finished this. I managed to make quite a mess of the git history here so I squashed it all into one commit and wiped the rest away. I've changed history, so, be careful of that.

**Comment by dmcbride** [comment]
Main issue is that the tooltips aren't coming up for me here, not sure why.  So I don't know what all the icons mean :(

**Comment by dmcbride** [comment]
weird ... bring up the panel a second time and then the tooltips do come up.

**Comment by dmcbride** [comment]
@1vasari - the escape key doesn't work again... :)

**Comment by 1vasari** [comment]
@dmcbride Ah... it must have gotten lost when I squashed all the commits. I knew *something* wouldn't work. :P

**Pull request closed without merging**
