### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by 1vasari**
lacuna ui 6

I don't think I need to explain much. The screenshot says it all, really. :smile: 

# Known Issues

- The planet map doesn't center correctly.
- Tiles on the planet map sometimes jump on hover.
- You can't self-destruct your empire because I just haven't put the button anywhere.
- The About window's server version field is using the default value (`123456789`) instead of the value from the server. :smiling_imp: 
- Stats looks ugly. :sob:
- Pressing the 'Send Message' button on an empire's profile is broken. The windows all hide but the messaging panel doesn't open.
- When you log out the background does not go back to the star field image. It just goes grey.

# Things That Need Looking At

- The loader does not stand out very well. At the moment I'm just using a loader that comes with Semantic UI but anything could be used. Heck, we could use the old spinner. :stuck_out_tongue_closed_eyes: 
- To me, the chat bar looks slightly out of place. Perhaps because it's smaller, I'm not sure. Any ideas on this?

# Notes

- The chat will connect the the US1 Firebase by default. The only time this changes is on PT, in which case (obviously) it connects to the Firebase for PT. This means you can now use chat in development mode. :yum:
- There are some changes to *could* be made to the `index.html` and `local.html` files for each server. In summary: most of the stuff in the `<body>` tag can get deleted because the new UI handles it.

I have tested this stuff on Chrome, Firefox, Safari, Opera and IE. It works well on all of them (except for Rhu's copy of Firefox, lol). :grinning: 

I've been hesitant to send this PR as I keep finding things to fix. But I think it *might* be in a state that can be put on PT and subject to the scrutiny of the Expanse.

Anyway, that should be it. :sparkles:

### CODE REVIEW

**Comment by 1vasari** [comment]
@dmcbride this is going to be a fun merge. :)

**Comment by icydee** [comment]
You should do the following...
1) do a rebase of your semantic code on top of the plainblack master
2) re-submit your pull request.

This means that you (who know best) can resolve any conflicts and then your pull request can be an easy fast-forward

**Comment by icydee** [comment]
It can't actually be automatically merged so I will close this request and you can re-submit it when you have done the above... (no hard feelings?)

**Comment by 1vasari** [comment]
Haha. That makes a lot more sense than leaving it to @dmcbride. :palm_tree: 

Working on it now.

**Pull request closed without merging**
