### PR TITLE
New planet map!

### PR DESCRIPTION
**Pull request by 1vasari**
Screenshot

:boom::boom:

### CODE REVIEW

**Comment by dmcbride** [comment]
This branch looks like it needs rebasing :)

**Comment by icydee** [comment]
This proved a bit big for me to rebase myself.

also the same point about separation of concerns. Could you split the classes in the map into separate files please using the 'map' file directory hierarchy?

**Comment by 1vasari** [comment]
Can you leave the PR open so I can fix it?

**Comment by icydee** [comment]
open, but rebased code will need a new PR

**Comment by 1vasari** [comment]
Status update here: I'm unhappy with this implementation so it's on the back burner until I think of a better solution.

**Comment by icydee** [comment]
closed by request.

**Pull request closed without merging**
