### PR TITLE
Sitter manager window

### PR DESCRIPTION
**Pull request by 1vasari**

### CODE REVIEW

**Comment by icydee** [comment]
The same applies to this I am afraid. I think that we should adopt the rule of one react class per file. I know this will lead to a lot more files but it will help to make the code easier to maintain with a 'separation of concerns'.

Please factor out the separate classes into separate files, in a suitable file hierarchy. (e.g. windows/sitter/authorized windows/sitter/current etc.)

**Comment by 1vasari** [comment]
Can you leave the PR open so I can fix it?

**Comment by icydee** [comment]
ditto.

**Comment by 1vasari** [comment]
@icydee done.

**Comment by icydee** [comment]
pulled, merged and put onto PT. (thank you)

**Pull request closed without merging**
