### PR TITLE
Meet Tabber

### PR DESCRIPTION
**Pull request by 1vasari**
This PR implemented a wrapper around `react-tabs`, affectionately know as Tabber. 

Tabber supports callbacks when individual tabs are selected. 
Tabber is *beautiful*. 
Tabber is your friend.

### CODE REVIEW

**Comment by dmcbride** [comment]
One thing I'm not a big fan of with these tab things is the separation of data - you have to manage the order of the tab names and tab contents independently, making things like reordering tabs much more error-prone.

If the tabs were each their own object, with a title and a content, and you could just loop through them, that would make more sense to me.  (Data-oriented design principles.)

**Comment by icydee** [comment]
I have had a look at the code and although I agree with @dmcbride to some extent, the way the code is written, although the tab names (titles) and the content are separate, they are very close together so easy to compare. Also, if some of the tab content were to be re-used (for example trades) I know that currently the title is not always the same (e.g. 'Trades' in the Trade Ministry, and 'Available Trades' in the SST) so I am happy to keep it like this.

However, I will ask that the separate Panel objects, BoostsPanel and GetEssentiaPanel are factored out into separate modules, components/window/essentia/boostPanel and components/window/essentia/essentiaPanel at the minimum. I would actually like to see one React class per file (as per the very first rule at https://github.com/airbnb/javascript/tree/master/react ) so that would mean factoring out the classes, BoostCountdown, Boost, BoostsPanel GetEssentiaPanel into their own files.

Would you please rebase this code and try out this approach for the Essentia Tabbed panel and we can see how it looks.

**Comment by 1vasari** [comment]
Sure. But does this PR need to be closed? I would prefer to make changes in this branch and keep it all together.

**Comment by 1vasari** [comment]
Can you leave the PR open so I can fix it?

**Comment by icydee** [comment]
I can leave the PR open, but if it needs to be rebased this PR will not work I don't think. Another PR will need to be created for the new rebased code.

**Comment by icydee** [comment]
pulled, merged and pushed to PT
(thank you)

**Pull request closed without merging**
