### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by 1vasari**
lacuna ui 6

I don't think I need to explain much. The screenshot says it all, really. :smile: 

# Known Issues

- The planet map doesn't center correctly.
- Tiles on the planet map sometimes jump on hover.
- You can't self-destruct your empire because I just haven't put the button anywhere.
- The About window's server version field is using the default value (`123456789`) instead of the value from the server. :smiling_imp: 
- Stats looks ugly. :sob:
- Pressing the 'Send Message' button on an empire's profile is broken. The windows all hide but the messaging panel doesn't open.
- When you log out the background does not go back to the star field image. It just goes grey.
- The RPC counter got lost in all this. I'll figure out where to put it sometime.

# Things That Need Looking At

- The loader does not stand out very well. At the moment I'm just using a loader that comes with Semantic UI but anything could be used. Heck, we could use the old spinner. :stuck_out_tongue_closed_eyes: 
- To me, the chat bar looks slightly out of place. Perhaps because it's smaller, I'm not sure. Any ideas on this?

# Notes

- The chat will connect the the US1 Firebase by default. The only time this changes is on PT, in which case (obviously) it connects to the Firebase for PT. This means you can now use chat in development mode. :yum:
- There are some changes to *could* be made to the `index.html` and `local.html` files for each server. In summary: most of the stuff in the `<body>` tag can get deleted because the new UI handles it.

I have tested this stuff on Chrome, Firefox, Safari, Opera and IE. It works well on all of them (except for Rhu's copy of Firefox, lol). :grinning: 

I've been hesitant to send this PR as I keep finding things to fix. But I think it *might* be in a state that can be put on PT and subject to the scrutiny of the Expanse.

Anyway, that should be it. :sparkles:

### CODE REVIEW

**Comment by icydee** [comment]
Probably best not to merge this until a test build on another server solves the following problems I am having.

 * I think that 'express' needs to be added as a dependency is package.json
 * I still get errors concerning 'Cannot find module classNames'

**Comment by 1vasari** [comment]
@icydee 

I accidentally removed the express dependency from the `package.json`. It's back in, now. :cop:

The `classnames` module was specified in the `package.json` but you need to run `npm install` to download it. Then it can get pulled into the JS build. This is a Node thing. Every time the `package.json` file changes you should run `npm install` to make sure your dependencies are up-to-date. (cc @lemming552 and @dmcbride)

**Comment by dmcbride** [comment]
the npm install is automatic on pt and should be on us1, but yeah, when doing local development, it's fun to remember :)

**Comment by dmcbride** [comment]
This is merged into my own branch and seems to be working, will try to get to pt as soon as I can.

**Comment by icydee** [comment]
@vasari
yes, did all that (multiple times) I still have the same error

[icydee@li352-106 Lacuna-Web-Client]$ npm install classnames
classnames@2.1.2 node_modules/classnames
[icydee@li352-106 Lacuna-Web-Client]$ npm install
pnotify@2.0.1 node_modules/pnotify
[icydee@li352-106 Lacuna-Web-Client]$ gulp dev
[07:45:28] Using gulpfile ~/sandbox/Lacuna-Web-Client/Gulpfile.js
[07:45:28] Starting 'browserify'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'classNames' from
'/home/icydee/sandbox/Lacuna-Web-Client/app/js/components/menu'
    at
/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process
(/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir
(/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load
(/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex
(/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at
/home/icydee/sandbox/Lacuna-Web-Client/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)



On 20 June 2015 at 06:43, Darin McBride <notifications@github.com> wrote:

> This is merged into my own branch and seems to be working, will try to get
> to pt as soon as I can.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plainblack/Lacuna-Web-Client/pull/72#issuecomment-113712924>
> .
>



-- 
Kind Regards
Iain

**Comment by dmcbride** [comment]
icy, Vas fixed that with c79eebf

**Comment by dmcbride** [comment]
@1vasari, your highlighting fix isn't quite right.  Sometimes some of the numbers are still red when they shouldn't be.  This is related to a recent fix I made to the space port - the numbers that come back from the server aren't numbers, they're strings.  So when we then compare with = or < or whatever, you're comparing strings instead of numbers, and that doesn't quite work.  Somehow, many of these numbers are actually numbers by the time we get to rendering the production tab, but sometimes some of them are not numbers anymore.

The old code does this starting on line 470 of game.jsx, but your body store should probably do similarly.

**Comment by 1vasari** [comment]
@dmcbride I didn't notice that happening but I'll take a closer look.

btw, you're idea that that should be done in the body store is exactly right. No playing around with data in the components, that's ugly and hard to reuse.

**Comment by 1vasari** [comment]
@dmcbride I believe I've fixed the numbers deal. 

I suspect that over time the stores will end up doing a fair bit to the data. But I think that that's fine as long as it's all happening in the one place. :whale:

**Comment by dmcbride** [comment]
Notes window: sweet.  Two points.  First is that it doesn't load the current planet's notes when I switch planets, whether the notes window is open or not (it gets the notes from the first planet I load, but never switches back).  Second is that the autosave is nice, but so is a button to save immediately.  Also, what to do when switching colonies?  Autosave, I presume.

The "progress" bars indicating fullness of each storage type are a bit tough to read, I think.  Especially when they're all full, they appear to run into each other.

I'm also missing the tick for the body storages where the storages auto fill (or empty) based on production, to their maximums, but I assume that'll come later.

**Comment by dmcbride** [comment]
I'm going to merge this into pt soon for wider testing, but the notes weirdness is improved, just not quite fixed :) Please test this against pt with multiple planets, switching between them, both with the notes window open and not open, changing text, etc., because, while this is an improvement, it's still pretty hokey.

Also, when opening the right sidebar (planets/stations), some sort of indication what the current location is would be nice.

**Comment by dmcbride** [comment]
Also, RPC counter on starmap is probably useful, too :)

**Comment by 1vasari** [comment]
Woopsie. I totally forgot to make planet switching work. :stuck_out_tongue: 

I'll get on that lol.

**Comment by 1vasari** [comment]
@dmcbride the RPC counter appears while on the starmap. Are you talking about something else?

**Comment by dmcbride** [comment]
hmmm - it didn't seem to be before, but that seems to work now, so nevermind :) though the part where if I try to push the colony map up as high as possible and the bottom row still overlaps the bottom status bar seems to come back periodically, though not consistently yet.

**Pull request merged**
