### PR TITLE
Improvements to sidebar

### PR DESCRIPTION
**Pull request by 1vasari**
This PR improves the sidebars by implementing `show` and `hide` actions for them instead of the generic `toggle`. This also fixes the warnings about moving sidebars around in the DOM and the React root container message. These were both (apparently) being caused by Semantic deciding to move stuff around in the DOM and React getting confused.

### CODE REVIEW

**Comment by icydee** [comment]
nice one :)

**Comment by icydee** [comment]
Once this is merged to master I will merge your changes into my code branch and make similar changes to the right sidebar.

**Comment by 1vasari** [comment]
I don't follow. I did both the left and right sidebars. Are you talking about something else?

**Comment by icydee** [comment]
oops, my mistake, I thought you had only done the left hand side! (goes back to sleep)

**Pull request merged**
