### PR TITLE
Add RPC count to bottom left.

### PR DESCRIPTION
**Pull request by 1vasari**
This PR implements [Dwarven Ire's forum request](http://community.lacunaexpanse.com/forums/developers/add-rpc-count-to-web-client) which was to add an RPC counter that's always visible.

### CODE REVIEW

**Comment by dmcbride** [comment]
A few comments here.

1. That was fast, nice :)
2. Try not to use master for pull requests - it'll make your life difficult :)
3. The font looks odd and out of place, may need some tweaking there.
4. The bottom of the window is reserved for the chat system.  And some of us fill up that bottom bar :)

I'm wondering if there's another place we could put it?  Perhaps a nice floating window like the incoming ships, but near the bottom right instead?  And maybe have "RPCs" be a link to the wiki ... if we had a good page describing RPCs I suppose. :)

**Comment by 1vasari** [comment]
A few responses:

    1. :1234: 
    2. I won't in future. Master was convenient because it had all of the commits of late in one place.
    3. Yes. It's too big. I'll look at that when I get a chance.
    4. That's fair enough. I never have more than three chats up at one time.

I didn't want to clog the UI too much so I'm hesitant to put *another* thing into the main view. I'll think about this and try find somewhere better.

**Comment by icydee** [comment]
How about treating it like the bottom left menu items for food/energy/water/ore. After all it is sort of a 'resource' which is used up each day.

Display it in the same way. At the top is the number of RPC used today, at the bottom is the max (for this server, 10k) and the bar shows the percentage of the RPC used.

**Comment by 1vasari** [comment]
Interesting idea. Though I'm not sure that putting an empire-wide resource alongside planet-specific resources would make much UI-sense.

**Comment by dmcbride** [comment]
Empire-wide stats are at the top left - same idea, but putting it between essentia and self-destruct might make sense, if it can look right?

**Comment by lemming552** [comment]
I vote for upper left as well.

**Comment by 1vasari** [comment]
:+1: 

I'll take a shot at the upper left when I get some time.

**Comment by 1vasari** [comment]
Done. Any further thoughts @dmcbride @lemming552 ??

**Comment by dmcbride** [comment]
Awesome.  Thanks, live on pt.

**Pull request closed without merging**
