### PR TITLE
MASSIVE changes to code layout and build process.

### PR DESCRIPTION
**Pull request by 1vasari**
The PR title and commit message explain most of what's happened here. Each change I've made I'll break down, a little:

- The directory structure of the code has been changed. This is to facilitate changes below, mostly. However, having all the files for the client in the root of the project, doesn't make much sense. It's messy, hard to find stuff, etc.
- This is the big one, `load.js` shows this off. We're now using Nodejs-style `require` calls to load all the different files. This is not as exciting as it may sound, unfortunately. In Node or Perl you can have modules and you use `require` or `use` to get them and they export stuff to be used. Currently, only half the deal is actually implemented. All the modules in the client get `required` but they still just attach themselves to `YAHOO.lacuna` rather than exporting functions back the `require`'er. My plan is to slowly transition the code so that it's using `require`s everywhere and not clogging the global `window` object.
- I've used Gulp (like make or rake, but for Node) to handle all the building of the code. All of that is documented in the readme. 
- The last major thing here is that I've put a copy of YUI into the repo. The reasoning is not particularly significant considering the (small) gain. My computer takes ages and ages to download YUI on my (very bad) Aussie internet. So, I've put a local copy of YUI which the client uses in development. I'm no lawyer but I don't believe there's a licencing problem, here.
- The client can now have environment-specific code. `process.env.NODE_ENV` will be either 'production' or 'development' and the build handles all that.

You guys are mostly Perl programmers, so if not much if that made sense, here are the important bits:

- The JavaScript code is smashed into one file, that is,  `/public/load.js`.
- It's possible to split the CSS into multiple files.
- Minified and un-minified versions are available (including CSS!).
- 'development' and 'production' modes are handled inside the JavaScript code.
- The process of sorting out and re factoring the code has started! :grinning:

I hope that it's not too problematic for this to get merged. :dizzy:

### CODE REVIEW

**Comment by 1vasari** [comment]
@lemming552 @dmcbride 

I don't mean to be a little bugger, but, what's the status on this?

**Comment by lemming552** [comment]
All in the timing.  You submitted this just before my roadtrip and I won't be back until Friday.

**Comment by 1vasari** [comment]
Woops. :)

Enjoy your trip then @lemming552. :grinning:

**Comment by 1vasari** [comment]
@lemming552 @dmcbride 

My recent commit "Straighten naming funk." has changed a few things:

- The directory containing all the built files has now been renamed to `build`.
- The built JS file has been renamed from `load.js` to `lacuna.js`.
- The development web server's port has been changed from `80` to `8080`.

So (if I understand this correctly), in `/local.html` the JS should be found at `http://localhost:8080/build/lacuna.js` and in `/index.html` it *should be* `http://<cdn url>/build/lacuna.min.js`.

I'm going to stop changing things and let you guys try and make it work, now. ;)

**Pull request closed without merging**
